name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -sdk iphoneos -scheme 'Networking-Package'
    - name: Run tests
      run: xcodebuild test -destination 'platform=Simulator,name=iPhone 11' -scheme 'Networking-Package'
