name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 8', 'platform=iOS Simulator,OS=13.1,name=iPhone 9']
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -sdk iphoneos -scheme 'Networking-Package'
    - name: Run tests
      run: xcodebuild test -destination "${destination}" -scheme 'Networking-Package'
      env:
        destination: ${{ matrix.destination }}
